"""Compile the vendored Stratus Sift JSON catalogue into C data.

Run from this directory with: python generate_rules.py
The source catalogue is pinned to Stratus-Security/Sift cf6a3ac42e98e78e54e9cdfeea56a9dfb0c21635.
"""

import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
DATA = HERE / "upstream-rules"
OUTPUT = HERE / "generated_rules.h"
PROFILE_SOURCE = (HERE / "upstream-profile.txt").read_text(encoding="utf-8")
PROFILE = re.findall(r'"(\.[^"\s]+)"', PROFILE_SOURCE)
PROFILE.insert(0, "")


def c_string(value):
    return '"' + value.encode("utf-8").decode("utf-8").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r") + '"'


def flag(value):
    return "1" if value else "0"


def pcre_pattern(pattern):
    """Translate leading variable-length .NET lookbehinds to PCRE2's keep operator."""
    if not pattern.startswith("(?<="):
        return pattern
    depth, in_class, escaped = 1, False, False
    for index in range(4, len(pattern)):
        char = pattern[index]
        if escaped:
            escaped = False
        elif char == "\\":
            escaped = True
        elif char == "[":
            in_class = True
        elif char == "]":
            in_class = False
        elif not in_class and char == "(":
            depth += 1
        elif not in_class and char == ")":
            depth -= 1
            if depth == 0:
                return "(?:" + pattern[4:index] + ")\\K" + pattern[index + 1:]
    raise ValueError(f"Unbalanced lookbehind: {pattern}")


rules = []
patterns = []
keywords = []
ignores = []


def add_rule(rule, parent=-1, inherited_extensions=""):
    index = len(rules)
    rules.append(rule)
    for match in rule.get("Matches", []):
        target = match.get("Target", "Content")
        extensions = list(match.get("IncludedExtensions", []))
        if match.get("ExtensionProfile") == "SourceAndConfig":
            extensions.extend(PROFILE)
        if target == "Content" and not extensions:
            extensions = inherited_extensions.split("|") if inherited_extensions else []
        extensions = "|".join(dict.fromkeys(extensions))
        for pattern in match.get("Patterns", []):
            keyword_start = len(keywords)
            keyword_values = match.get("Keywords", [])
            if not any(value.endswith("|") for value in keyword_values):
                keywords.extend(keyword_values)
            regex = not match.get("IsLiteral", False) and (target == "Content" or
                (target in ("FileName", "DirectoryName", "DirectoryPath") and
                 any(char in pattern for char in "*?[\\^$+{|()")))
            patterns.append((index, target, pcre_pattern(pattern) if regex else pattern, regex,
                             match.get("CaseSensitive", False), extensions,
                             keyword_start, len(keywords) - keyword_start))
        if target == "Content" and extensions:
            inherited_extensions = extensions
    for child in rule.get("SubRules", []):
        add_rule(child, index, inherited_extensions)


for source in sorted((DATA / "Rules").rglob("*.json")):
    item = json.loads(source.read_text(encoding="utf-8-sig"))
    for rule in item if isinstance(item, list) else [item]:
        add_rule(rule)

for source in sorted((DATA / "IgnoreRules").rglob("*.json")):
    item = json.loads(source.read_text(encoding="utf-8-sig"))
    ignores.extend(item if isinstance(item, list) else [item])

lines = [
    "/* Generated by generate_rules.py from the pinned upstream Sift catalogue. */",
    "#ifndef SIFT_GENERATED_RULES_H",
    "#define SIFT_GENERATED_RULES_H",
    "typedef struct { const char *name, *severity, *validator, *exclude; int parent, enabled, report; double entropy; } sift_rule;",
    "typedef struct { int rule; const char *target, *pattern, *extensions; int regex, case_sensitive, keyword_start, keyword_count; } sift_pattern;",
    "typedef struct { const char *target, *pattern; int enabled; } sift_ignore;",
    "static const sift_rule sift_rules[] = {",
]
for i, rule in enumerate(rules):
    parent = next((p for p in range(i) if rule in rules[p].get("SubRules", [])), -1)
    fields = (c_string(rule["Name"]), c_string(rule.get("Severity", "Medium")),
              c_string(rule.get("Validator", "")), c_string("|".join(rule.get("ExcludePaths", []))),
              str(parent), flag(rule.get("Enabled", True)), flag(rule.get("ReportFinding", True)),
              str(rule.get("EntropyThreshold", 0)))
    lines.append("    {" + ", ".join(fields) + "},")
lines.extend(("};", "static const sift_pattern sift_patterns[] = {"))
for rule, target, pattern, regex, case_sensitive, extensions, keyword_start, keyword_count in patterns:
    fields = (str(rule), c_string(target), c_string(pattern), c_string(extensions),
              flag(regex), flag(case_sensitive), str(keyword_start), str(keyword_count))
    lines.append("    {" + ", ".join(fields) + "},")
lines.extend(("};", "static const char *sift_keywords[] = {"))
for keyword in keywords:
    lines.append("    " + c_string(keyword) + ",")
lines.extend(("};", "static const sift_ignore sift_ignores[] = {"))
for ignore in ignores:
    fields = (c_string(ignore.get("MatchTarget", "FileName")), c_string(ignore["Pattern"]),
              flag(ignore.get("IsEnabled", True)))
    lines.append("    {" + ", ".join(fields) + "},")
lines.extend(("};", "#define SIFT_RULE_COUNT (sizeof(sift_rules) / sizeof(sift_rules[0]))",
              "#define SIFT_PATTERN_COUNT (sizeof(sift_patterns) / sizeof(sift_patterns[0]))",
              "#define SIFT_IGNORE_COUNT (sizeof(sift_ignores) / sizeof(sift_ignores[0]))",
              "#endif"))
OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {len(rules)} rules, {len(patterns)} patterns, {len(keywords)} keyword references, {len(ignores)} ignores")
