import {Component, useEffect, useMemo, useRef, useState, type ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {Terminal} from '@xterm/xterm';
import {ArrowRight, Boxes, Cable, Clock3, Computer, Download, ListTodo, MessagesSquare, Network, Radio, RefreshCw, Route as RouteIcon, Settings, SquareTerminal, X} from 'lucide-react';
import {api, connect, csrfToken, type Agent, type Job, type Status, type Topology} from './api';
import {TopologyGraph} from './TopologyGraph';
import {HostResults} from './HostResults';
import {RoutesView} from './RoutesView';
import {PayloadView} from './PayloadView';
import {DeploymentsView} from './DeploymentsView';
import {ModulesView} from './ModulesView';
import {JobsView} from './JobsView';
import {ScreenshotsView} from './ScreenshotsView';
import {FilesView} from './FilesView';
import {AgentLifecycle, ForwardsView, RoutingModeView, TransportsView} from './OperationalControls';
import {WorkerLogsView} from './WorkerLogsView';
import {OperatorSettings, type OperatorAccount} from './OperatorSettings';
import {TransfersView} from './TransfersView';
import {TeamView} from './TeamView';
import '@xyflow/react/dist/style.css';
import '@xterm/xterm/css/xterm.css';
import './style.css';
import './workflows.css';
import './screenshots.css';
import './files.css';
import './controls.css';
import './agent-payload-hosting.css';

type View = 'topology'|'agents'|'deployments'|'jobs'|'transfers'|'routes'|'relays'|'forwards'|'modules'|'payloads'|'team'|'history'|'settings';
type Audit = {id:string;at:string;action:string;target:string;client_id?:string;client_session_id?:string;operator_id?:string;display_name?:string;source:string;identity_trust:string;status:number};
const nav: {id:View; label:string; icon:typeof Network}[] = [
  {id:'topology',label:'Topology',icon:Network},{id:'agents',label:'Agents',icon:Computer},{id:'deployments',label:'Jump',icon:ArrowRight},{id:'jobs',label:'Jobs',icon:ListTodo},{id:'transfers',label:'Transfers',icon:Download},
  {id:'routes',label:'Routes',icon:RouteIcon},{id:'relays',label:'Relays',icon:Cable},{id:'forwards',label:'Forwards',icon:Cable},{id:'modules',label:'Modules',icon:Boxes},{id:'payloads',label:'Payloads',icon:Boxes},{id:'team',label:'Team',icon:MessagesSquare},{id:'history',label:'History',icon:Clock3},{id:'settings',label:'Settings',icon:Settings}
];
function formatTime(value?:string){return value&&!value.startsWith('0001-')?new Date(value).toLocaleString():'—'}
function short(value:string){return value.length>18?value.slice(0,18)+'…':value}

function visibleTopology(topology:Topology|null,showArchived:boolean):Topology|null{
  if(!topology||showArchived)return topology;
  const hidden=new Set(topology.nodes.filter(node=>node.kind==='agent'&&node.archived&&!node.active).map(node=>node.id));
  for(const node of topology.nodes){
    if(node.kind==='relay'&&!node.active&&node.agent_id&&hidden.has(`agent:${node.agent_id}`))hidden.add(node.id);
  }
  const edges=topology.edges.filter(edge=>!hidden.has(edge.source)&&!hidden.has(edge.target));
  const connectedNodes=new Set(edges.flatMap(edge=>[edge.source,edge.target]));
  const nodes=topology.nodes.filter(node=>!hidden.has(node.id)&&(node.kind!=='network'||connectedNodes.has(node.id)));
  const nodeIDs=new Set(nodes.map(node=>node.id));
  return {...topology,nodes,edges:edges.filter(edge=>nodeIDs.has(edge.source)&&nodeIDs.has(edge.target))};
}

function App(){
  const [ready,setReady]=useState(false), [authError,setAuthError]=useState<'expired'|'link'|''>(''), [error,setError]=useState('');
  const refreshSequence=useRef(0);
  const [view,setView]=useState<View>('topology'), [status,setStatus]=useState<Status|null>(null), [topology,setTopology]=useState<Topology|null>(null);
  const [showArchived,setShowArchived]=useState(false);
  const [relayTarget,setRelayTarget]=useState<{agentID:string;bind:string}|null>(null);
  const [renameAgentID,setRenameAgentID]=useState<string|null>(null);
  const [selectedDeployment,setSelectedDeployment]=useState<string|null>(null);
  const [selectedJob,setSelectedJob]=useState<string|null>(null);
  const [selected,setSelected]=useState<string|null>(null), [tab,setTab]=useState('Console'), [jobs,setJobs]=useState<Job[]>([]), [relays,setRelays]=useState<{agent_id:string;bind:string;state?:string}[]>([]), [history,setHistory]=useState<Audit[]>([]);
  const [client,setClient]=useState<{session_id:string;transport:string;server_address:string;operator_only:boolean;vpn:boolean;internal:boolean}|null>(null), [busy,setBusy]=useState(false);
  const [operator,setOperator]=useState<OperatorAccount|null>(null);
  useEffect(()=>{const expired=()=>setAuthError('expired');window.addEventListener('undertow-auth-expired',expired);return()=>window.removeEventListener('undertow-auth-expired',expired)},[]);
  const snapshot=<T,>(path:string):Promise<T>=>{const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),8000);return api<T>(path,'GET',undefined,controller.signal).finally(()=>window.clearTimeout(timeout))};
  const refresh=async()=>{
    const sequence=++refreshSequence.current;
    const [s,t,j,r,c,h,o]=await Promise.allSettled([snapshot<Status>('/status'),snapshot<Topology>('/topology'),snapshot<Job[]>('/jobs'),snapshot<{agent_id:string;bind:string}[]>('/relays'),snapshot<{session_id:string;transport:string;server_address:string;operator_only:boolean;vpn:boolean;internal:boolean}>('/client'),snapshot<Audit[]>('/history'),snapshot<OperatorAccount>('/operator/me')]);
    if(sequence!==refreshSequence.current)return;
    if(s.status==='fulfilled')setStatus(s.value);
    if(t.status==='fulfilled')setTopology(t.value);
    if(j.status==='fulfilled')setJobs(j.value);
    if(r.status==='fulfilled')setRelays(r.value);
    if(c.status==='fulfilled')setClient(c.value);
    if(h.status==='fulfilled')setHistory(h.value);
    if(o.status==='fulfilled')setOperator(o.value);else setOperator(null);
    setError(s.status==='rejected'?String(s.reason):'');
  };
  useEffect(()=>{connect().then(()=>{setReady(true);void refresh();void api<{show_archived:boolean}>('/preferences').then(p=>setShowArchived(p.show_archived)).catch(e=>setError(String(e)))}).catch(e=>setAuthError(e instanceof Error&&e.message==='session_expired'?'expired':'link'))},[]);
  useEffect(()=>{if(!ready||authError)return;const source=new EventSource('/api/events');let timer:number|undefined;source.onopen=()=>{void refresh();window.dispatchEvent(new Event('undertow-team-changed'));window.dispatchEvent(new Event('undertow-team-roster-changed'))};source.onerror=()=>{void refresh()};source.addEventListener('change',event=>{try{const {kind,target}=JSON.parse((event as MessageEvent).data) as {kind:string;target?:string};if(kind==='worker_log')return;if(kind==='team.changed'){window.dispatchEvent(new Event('undertow-team-changed'));return}if(kind==='audit.recorded'){void snapshot<Audit[]>('/history').then(setHistory).catch(()=>{});return}if(kind==='operation.changed'&&target?.startsWith('/v1/team/'))return;if(kind==='operation.changed'&&target?.startsWith('/v1/operators'))window.dispatchEvent(new Event('undertow-team-roster-changed'));if(kind==='resync_required'){window.dispatchEvent(new Event('undertow-team-changed'));window.dispatchEvent(new Event('undertow-team-roster-changed'))}}catch{}if(timer)window.clearTimeout(timer);timer=window.setTimeout(()=>refresh(),150)});return()=>{source.close();if(timer)window.clearTimeout(timer)}},[ready,authError]);
  const agents=useMemo(()=>status?.agents.filter(a=>showArchived||!a.archived)||[],[status,showArchived]);
  const graph=useMemo(()=>visibleTopology(topology,showArchived),[topology,showArchived]);
  const activeAgent=agents.find(a=>a.id===selected);
  const changeArchivedVisibility=async(show:boolean)=>{try{await api('/preferences/archived-visibility','PUT',{show_archived:show});setShowArchived(show)}catch(e){setError(String(e))}};
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
  if(authError)return <div className="auth-page"><section className="auth-dialog" role="alertdialog" aria-modal="true" aria-labelledby="auth-title" aria-describedby="auth-description"><div className="auth-dialog-brand"><div className="brand-mark">U</div><span>UNDERTOW · OPERATOR CLIENT</span></div><div className="auth-dialog-body"><span className="auth-dialog-kicker">LOCAL GUI ACCESS</span><h1 id="auth-title">{authError==='expired'?'Session expired':'Open a fresh GUI link'}</h1><p id="auth-description">{authError==='expired'?'Your local browser session has ended. The client and its agents are unaffected.':'This browser link is missing its launch token or can no longer be used.'}</p><div className="auth-dialog-steps"><span>1</span><p>In the Undertow client console, run:</p><code>undertow client gui</code><span>2</span><p>Open the complete URL it prints in this browser.</p></div><small>The new URL includes a per-launch token. Copy the full link, including the part after #.</small></div></section></div>;
  if(!ready)return <div className="auth-page">Connecting to local client…</div>;
  return <div className="app-shell">
    <aside className="nav-rail"><div className="brand"><div className="brand-mark">U</div><div><strong>UNDERTOW</strong><small>OPERATOR CLIENT</small></div></div>
      <div className="nav-heading">WORKSPACE</div><nav>{nav.map(item=><button key={item.id} aria-label={item.label} title={item.label} className={'nav-item '+(view===item.id?'selected':'')} onClick={()=>setView(item.id)}><item.icon size={17}/><span>{item.label}</span>{item.id==='agents'&&status?<em>{agents.length}</em>:null}</button>)}</nav>
      <div className="nav-footer"><div className={'connection-dot '+(client?.session_id?'online':'offline')}/><div><strong>{operator?.display_name||'Disconnected'}</strong><small>{operator?`${operator.id} · ${operator.role==='team_leader'?'Team Leader':'Operator'}`:'Waiting for server'}</small></div></div>
    </aside>
    <div className="main-column"><header className="topbar"><div className="breadcrumb"><span>OPERATIONS</span><span className="slash">/</span><strong>{nav.find(n=>n.id===view)?.label}</strong>{activeAgent?<><span className="slash">/</span><span>{activeAgent.nickname||activeAgent.hostname||short(activeAgent.id)}</span></>:null}</div><div className="top-actions"><span className="carrier-pill"><Radio size={14}/>{client?.transport||'No carrier'}</span><button className="icon-button" title="Refresh" onClick={refresh}><RefreshCw size={17}/></button></div></header>
      {error&&<div className="error-banner"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss"><X size={15}/></button></div>}
      <main className="content">
        {view==='topology'&&<><PageHeader title="Network topology" description="Observed sessions, relay paths, routes, and operator clients." count={graph?.nodes.length} /><div className="topology-layout"><div className="topology-frame"><TopologyGraph topology={graph} localClient={client} onAgent={id=>{setSelected(id);setTab('Console');setView('agents')}} actions={{renameAgent:id=>{setSelected(id);setRenameAgentID(id);setView('agents')},archiveAgent:(id,archived)=>void act(()=>api(`/agents/${encodeURIComponent(id)}/archive`,'PUT',{archived})),killSession:id=>void act(()=>api(`/agents/${encodeURIComponent(id)}/session/kill`,'POST',{})),shutdownAgent:id=>void act(()=>api(`/agents/${encodeURIComponent(id)}/shutdown`,'POST',{})),openRoutes:()=>setView('routes'),removeRoute:(prefix,agentID)=>void act(()=>api(`/client/routes?prefix=${encodeURIComponent(prefix)}&agent_id=${encodeURIComponent(agentID)}`,'DELETE')),openRelays:()=>setView('relays'),stopRelay:(id,bind)=>void act(()=>api(`/agents/${encodeURIComponent(id)}/relays?bind=${encodeURIComponent(bind)}`,'DELETE')),openSettings:()=>setView('settings'),openDeployment:id=>{setSelectedDeployment(id);setView('deployments')}}}/></div><div className="side-stack"><section className="panel"><h2>Connected peers</h2><Metric label="Agents" value={status?.agents.filter(a=>a.online!==false).length||0}/><Metric label="Operator clients" value={status?.clients.length||0}/><Metric label="Active relays" value={relays.filter(r=>r.state!=='pending').length}/></section><section className="panel"><h2>Carrier listeners</h2>{(topology?.nodes.find(n=>n.kind==='server')?.carriers||['dns','quic','websocket'].map(transport=>({transport,active:!!status?.server.listeners?.some(l=>l.transport===transport),listen:status?.server.listeners?.find(l=>l.transport===transport)?.listen,sessions:status?.server.listeners?.find(l=>l.transport===transport)?.sessions}))).map(l=><div className={'listener-row '+(l.active?'':'inactive')} key={l.transport}><span className="state-indicator"/><div><strong>{l.transport.toUpperCase()}</strong><small>{l.active?l.listen:'Inactive'}</small></div><b>{l.active?l.sessions:'—'}</b></div>)}</section><section className="panel compact"><h2>Route legend</h2><Legend color="var(--amber)" label="Carrier / relay path"/><Legend color="var(--green)" label="Client accepted path"/><Legend color="#cd85dd" label="Active forward"/><Legend color="#92bdcf" label="Jump link"/></section></div></div></>}
        {view==='agents'&&<><PageHeader title="Agents" description="Select an agent to open its workspace." count={agents.length}/><div className="agent-layout"><div className="agent-list panel"><div className="panel-title">Agent records · {agents.filter(a=>a.online!==false).length} connected · {agents.filter(a=>a.connection_state==='sleeping').length} sleeping</div>{agents.length?agents.map(a=><button key={a.id} className={'agent-row '+(selected===a.id?'active':'')+(a.online===false&&a.connection_state!=='sleeping'?' disconnected':'')+(a.connection_state==='sleeping'?' sleeping':'')+(a.archived?' archived':'')} onClick={()=>{setSelected(a.id);setTab(a.online===false&&a.connection_state!=='sleeping'?'Overview':'Console')}}><span className={'agent-icon privilege-'+(a.privilege||'unknown')} title={privilegeLabel(a)}><Computer size={17}/></span><span className="agent-name"><strong>{a.nickname||a.hostname||short(a.id)}</strong><small>{a.nickname?`${a.hostname||short(a.id)} · `:''}{agentStateLabel(a)} · {a.os||'Unknown OS'} · {a.transport||'Unknown carrier'}</small></span><span className={"state-indicator "+(a.connection_state==='sleeping'?'sleeping':a.online===false?'offline':'')}/></button>):<Empty text={status?.agents.some(a=>a.archived)?'No visible agents. Show archived agents in Settings → Agents.':'No agent records yet'}/>}</div><div className="workspace panel">{activeAgent?<AgentWorkspace agent={activeAgent} agents={status?.agents||[]} jobs={jobs.filter(j=>j.agent_id===activeAgent.id)} tab={tab} setTab={setTab} act={act} busy={busy} onRefresh={refresh} revision={topology?.at} client={client} openRoutes={()=>setView('routes')} openDeployments={()=>{setSelectedDeployment(null);setView('deployments')}} renameRequested={renameAgentID===activeAgent.id} onRenameOpened={()=>setRenameAgentID(null)}/>:<div className="workspace-empty"><Computer size={35}/><h2>Select an agent</h2><p>Agent details and operations will appear here.</p></div>}</div></div></>}
        {view==='deployments'&&<><PageHeader title="Jump" description="Record, prepare, and track Windows jump requests."/><DeploymentsView agents={status?.agents||[]} initialSource={selected} initialRecord={selectedDeployment} revision={topology?.at} onAgent={id=>{setSelected(id);setTab('Overview');setView('agents')}} onJob={id=>{setSelectedJob(id);setView('jobs')}} onTransfers={()=>setView('transfers')}/></>}
        {view==='jobs'&&<><PageHeader title="Jobs" description="Background execution and retained server output." count={jobs.length}/><JobsView jobs={jobs} initialJobID={selectedJob} onRefresh={refresh} onAgent={id=>{setSelected(id);setTab('Jobs');setView('agents')}} onDeployment={id=>{setSelectedDeployment(id);setView('deployments')}}/></>}
        {view==='transfers'&&<><PageHeader title="Transfers" description="Server retained file transfer state and verification."/><TransfersView revision={topology?.at}/></>}
        {view==='routes'&&<><PageHeader title="Routes" description="Server routes and each client’s accepted paths." count={status?.routes.length}/><RoutingModeView client={client} onChange={refresh}/><RoutesView status={status} client={client}/></>}
        {view==='relays'&&<><PageHeader title="Relays" description="Listeners hosted by agents and child paths." count={relays.length}/><RelaysView agents={status?.agents.filter(a=>a.online!==false||a.connection_state==='sleeping')||[]} relays={relays} act={act} busy={busy} onPayload={target=>{setRelayTarget(target);setView('payloads')}}/></>}
        {view==='forwards'&&<><PageHeader title="Forwards" description="Agent TCP listeners that forward connections to this client."/><ForwardsView agents={status?.agents.filter(a=>a.online!==false||a.connection_state==='sleeping')||[]} revision={topology?.at}/></>}
        {view==='modules'&&<><PageHeader title="Module bank" description="Compiled modules loaded on this client. Select an agent before running one."/><ModulesView agents={status?.agents.filter(a=>a.online!==false||a.connection_state==='sleeping')||[]} onJobs={()=>setView('jobs')}/></>}
        {view==='payloads'&&<><PageHeader title="Payloads" description="Existing profiles and built artifacts on the server."/><PayloadView revision={topology?.at} serverAddress={client?.server_address} serverInfo={status?.server} publicHost={status?.server.public_host} clientTransport={client?.transport} relayTarget={relayTarget} agents={status?.agents||[]} relays={relays}/></>}
        {view==='team'&&<><PageHeader title="Team" description="Operator conversations and assignments retained by the server."/><TeamView self={operator} connected={!!client?.session_id}/></>}
        {view==='history'&&<><PageHeader title="Operational history" description="Server recorded operator actions and their results." count={history.length}/><div className="panel table-panel"><HistoryTable records={history} onDeployment={id=>{setSelectedDeployment(id);setView('deployments')}}/></div></>}
        {view==='settings'&&<SettingsView status={status} client={client} operator={operator} revision={topology?.at} onRefresh={refresh} showArchived={showArchived} onArchivedVisibility={changeArchivedVisibility}/>}
      </main>
    </div>
  </div>
}
function PageHeader({title,description,count}:{title:string;description:string;count?:number}){return <div className="page-header"><div><h1>{title}</h1><p>{description}</p></div>{count!==undefined&&<div className="count-card"><strong>{count}</strong><span>TOTAL</span></div>}</div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Legend({color,label}:{color:string;label:string}){return <div className="legend"><span style={{background:color}}/>{label}</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function HistoryTable({records,onDeployment}:{records:Audit[];onDeployment:(id:string)=>void}){return records.length?<table><thead><tr><th>Time</th><th>Action</th><th>Target</th><th>Operator</th><th>Client</th><th>Result</th></tr></thead><tbody>{records.map(r=>{const deploymentID=/^\/v1\/deployments\/([^/]+)/.exec(r.target)?.[1];return <tr key={r.id}><td>{formatTime(r.at)}</td><td className="mono">{r.action}</td><td className="mono">{deploymentID?<button className="deployment-link" onClick={()=>onDeployment(deploymentID)}>{r.target}</button>:r.target}</td><td>{r.display_name||r.operator_id||'Server console'}<small className="history-trust">{r.identity_trust.replaceAll('_',' ')}</small></td><td className="mono">{r.client_id?short(r.client_id):r.source}</td><td><span className={'badge '+(r.status===0?'warn':r.status<400?'good':'muted')}>{r.status||'Pending'}</span></td></tr>})}</tbody></table>:<Empty text="No operator actions recorded"/>}

function AgentWorkspace({agent,agents,jobs,tab,setTab,act,busy,onRefresh,revision,client,openRoutes,openDeployments,renameRequested,onRenameOpened}:{agent:Agent;agents:Agent[];jobs:Job[];tab:string;setTab:(s:string)=>void;act:(fn:()=>Promise<unknown>)=>void;busy:boolean;onRefresh:()=>Promise<void>;revision?:string;client:{operator_only:boolean;session_id:string}|null;openRoutes:()=>void;openDeployments:()=>void;renameRequested:boolean;onRenameOpened:()=>void}){
  if(agent.online===false&&agent.connection_state!=='sleeping'){
    const offlineTabs=['Overview','Console','Jobs','Screenshots','Host'];
    const current=offlineTabs.includes(tab)?tab:'Overview';
    return <><AgentHeader agent={agent} onRefresh={onRefresh} renameRequested={renameRequested} onRenameOpened={onRenameOpened}/><div className="offline-notice">Disconnected {formatTime(agent.disconnected_at)}. Last known details and retained history remain available. Agent actions are unavailable.</div><div className="tabs">{offlineTabs.map(name=><button key={name} className={current===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</div><div className="workspace-body offline-workspace">
      {current==='Overview'&&<div className="overview-grid"><Info label="Operating system" value={`${agent.os||'Unknown'} / ${agent.arch||'Unknown'}`}/><Info label="Last carrier" value={agent.transport||'Unknown'}/><Info label="Last remote address" value={agent.remote||'Unknown'}/><Info label="Observed public IP" value={agent.public_ip||'Not observed'}/><Info label="Relay parent" value={agent.via||'Direct'}/><Info label="Last seen" value={formatTime(agent.last_seen)}/><AgentSleep agent={agent} onRefresh={onRefresh}/><div className="wide"><h3>Last advertised routes</h3><div className="chips">{agent.advertised_routes?.map(prefix=><span key={prefix}>{prefix}</span>)||<span>None recorded</span>}</div></div><div className="wide"><h3>Last reported capabilities</h3><div className="chips">{agent.capabilities?.allowed?.map(capability=><span key={capability}>{capability}</span>)||<span>Not reported</span>}</div></div><div className="wide archive-control"><div><h3>{agent.archived?'Archived agent':'Archive agent'}</h3><p>{agent.archived?'This disconnected record is hidden unless archived agents are shown in Settings. Its history is retained.':'Hide this lost agent from Agents and Topology. Its history stays on the server, and a callback restores it automatically.'}</p></div><button disabled={busy} onClick={()=>act(()=>api(`/agents/${encodeURIComponent(agent.id)}/archive`,'PUT',{archived:!agent.archived}))}>{agent.archived?'Restore to agent list':'Archive agent'}</button></div></div>}
      {current==='Console'&&<AgentCommandConsole key={agent.id} agent={agent} openShell={()=>{}} readOnly/>}
      {current==='Jobs'&&<JobsView jobs={jobs} agentID={agent.id} onRefresh={onRefresh} readOnly/>}
      {current==='Screenshots'&&<ScreenshotsView agent={agent} revision={revision}/>}
      {current==='Host'&&<HostResults agentID={agent.id} sessionID={agent.session_id} offline revision={revision}/>}
    </div></>
  }
  const tabs=['Console','Overview','Files','Jobs','Screenshots','Modules','Host','Live shell'];
  return <><AgentHeader agent={agent} onRefresh={onRefresh} renameRequested={renameRequested} onRenameOpened={onRenameOpened}/>{agent.os?.toLowerCase()==='windows'&&<div className="deployment-agent-entry"><span>Jump</span><button onClick={openDeployments}>Create from this agent <ArrowRight size={14}/></button></div>}<div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="workspace-body">
    {tab==='Overview'&&<div className="overview-grid"><Info label="Operating system" value={`${agent.os||'Unknown'} / ${agent.arch||'Unknown'}`}/><Info label="Carrier" value={agent.transport||'Unknown'}/><Info label="Remote address" value={agent.remote||'Unknown'}/><Info label="Observed public IP" value={agent.public_ip||'Not observed from this connection'}/><Info label="Relay parent" value={agent.via||'Direct'}/><Info label="Last seen" value={formatTime(agent.last_seen)}/><Info label="Active jobs" value={String(agent.active_jobs||0)}/><div className="wide"><AgentOverviewRoutes agent={agent} agents={agents} client={client} openRoutes={openRoutes} onRefresh={onRefresh}/></div><div className="wide"><h3>Allowed capabilities</h3><div className="chips">{agent.capabilities?.allowed?.map(c=><span key={c}>{c}</span>)||<span>Not reported</span>}</div></div><AgentSleep agent={agent} onRefresh={onRefresh}/><AgentLifecycle agent={agent} onRefresh={onRefresh}/></div>}
    <div style={{display:tab==='Console'?'block':'none'}}><AgentCommandConsole key={agent.id} agent={agent} openShell={()=>setTab('Live shell')}/></div>
    <div style={{display:tab==='Files'?'block':'none'}}><FilesView key={agent.id} agentID={agent.id} revision={revision}/></div>
    {tab==='Jobs'&&<><StartJob agentID={agent.id} act={act} busy={busy}/><JobsView jobs={jobs} agentID={agent.id} onRefresh={onRefresh}/></>}
    {tab==='Screenshots'&&<ScreenshotsView agent={agent} revision={revision}/>}
    <div style={{display:tab==='Modules'?'block':'none'}}><ModulesView key={agent.id} agent={agent} onJobs={()=>setTab('Jobs')}/></div>
    {tab==='Host'&&<HostResults agentID={agent.id} sessionID={agent.session_id} revision={revision}/>}
    {tab==='Live shell'&&<LiveShellPanel key={agent.id} agentID={agent.id} online={agent.online!==false}/>}
  </div></>
}
function AgentHeader({agent,onRefresh,renameRequested,onRenameOpened}:{agent:Agent;onRefresh:()=>Promise<void>;renameRequested:boolean;onRenameOpened:()=>void}){
  const [editing,setEditing]=useState(false),[value,setValue]=useState(agent.nickname||''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{setEditing(false);setValue(agent.nickname||'');setError('')},[agent.id]);
  useEffect(()=>{if(renameRequested){setValue(agent.nickname||'');setEditing(true);onRenameOpened()}},[renameRequested,agent.nickname,onRenameOpened]);
  const save=async()=>{setSaving(true);setError('');try{await api(`/agents/${encodeURIComponent(agent.id)}/nickname`,'PUT',{nickname:value});await onRefresh();setEditing(false)}catch(e){setError(String(e))}finally{setSaving(false)}};
  return <><div className="workspace-header"><div className={'workspace-avatar privilege-'+(agent.privilege||'unknown')} title={privilegeLabel(agent)}><Computer size={25}/></div><div className="workspace-identity"><div className="eyebrow">{agent.archived?'ARCHIVED AGENT RECORD':agent.online===false&&agent.connection_state!=='sleeping'?'RETAINED AGENT RECORD':'AGENT WORKSPACE'}</div><h2>{agent.nickname||agent.hostname||agent.id}</h2><p>{agent.nickname?`${agent.hostname||'Unknown host'} · `:''}{agent.id}</p></div><button className="workspace-rename" onClick={()=>{setValue(agent.nickname||'');setEditing(!editing)}}>Rename</button><span className={'badge '+(agent.connection_state==='sleeping'?'sleeping':agent.online===false?'muted':'good')}>{agentStateLabel(agent)}</span></div>{editing&&<form className="agent-nickname-editor" onSubmit={event=>{event.preventDefault();void save()}}><label>Agent nickname<input autoFocus maxLength={48} aria-label="Agent nickname" value={value} onChange={event=>setValue(event.target.value)} placeholder={agent.hostname||'Agent nickname'}/></label><span>Shared with operators. Clear to show the hostname.</span><button disabled={saving} type="submit">Save name</button><button type="button" onClick={()=>setEditing(false)}>Cancel</button>{error&&<strong role="alert">{error}</strong>}</form>}</>;
}
function Info({label,value}:{label:string;value:string}){return <div className="info"><small>{label}</small><strong>{value}</strong></div>}
function agentStateLabel(agent:Agent){return agent.archived?'Archived':agent.connection_state==='sleeping'?'Sleeping':agent.online===false?'Disconnected':'Connected'}
function privilegeLabel(agent:Agent){return agent.privilege==='high'?'High privilege':agent.privilege==='low'?'Low privilege':'Privilege unknown'}
function sleepIntervalLabel(seconds:number){if(!seconds)return 'Continuous';if(seconds%3600===0)return `${seconds/3600}h`;if(seconds%60===0)return `${seconds/60}m`;return `${seconds}s`}
function AgentSleep({agent,onRefresh}:{agent:Agent;onRefresh:()=>Promise<void>}){
  const configured=agent.sleep?.interval_seconds||0,configuredJitter=agent.sleep?.jitter_percent||0;
  const [seconds,setSeconds]=useState(configured),[jitter,setJitter]=useState(configuredJitter),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  useEffect(()=>{setSeconds(configured);setJitter(configuredJitter);setSaved(false)},[agent.id,configured,configuredJitter]);
  const supported=!!agent.sleep_supported,editable=supported&&(agent.online!==false||agent.connection_state==='sleeping');
  const checkin=configured>0,plannedCheckin=seconds>0,dirty=seconds!==configured||jitter!==configuredJitter;
  const valid=Number.isInteger(seconds)&&seconds>=0&&seconds<=86400&&Number.isInteger(jitter)&&jitter>=0&&jitter<=50;
  const state=agentStateLabel(agent),mode=agent.connection_mode==='checkin'||checkin?'Check-in mode':'Continuous mode';
  const reason=agent.connection_reason||(!supported?'This agent build has no sleep support.':checkin?'Waiting for the agent to become idle.':'Configured to keep its session open.');
  const save=async()=>{setBusy(true);setError('');setSaved(false);try{await api(`/agents/${encodeURIComponent(agent.id)}/sleep`,'PUT',{interval_seconds:seconds,jitter_percent:jitter});await onRefresh();setSaved(true)}catch(e){setError(String(e))}finally{setBusy(false)}};
  return <section className={'wide agent-sleep '+(agent.connection_state==='sleeping'?'is-sleeping':'')} aria-label="Agent connection rhythm">
    <div className="agent-sleep-head"><div className="agent-sleep-mark"><Clock3 size={20}/></div><div><span className="agent-sleep-kicker">CONNECTION RHYTHM</span><h3>{mode}</h3><p>{checkin?`Configured interval ${sleepIntervalLabel(configured)} · jitter ±${configuredJitter}%`:'Persistent session while the agent remains reachable'}</p></div><span className={'agent-sleep-state '+(agent.connection_state==='sleeping'?'sleeping':agent.online===false?'lost':'connected')}>{state}</span></div>
    <div className="agent-sleep-summary"><strong>{reason}</strong>{checkin&&<span>{agent.sleep_protocol_version&&agent.sleep_protocol_version<2?'Legacy build waits for the full interval before sleeping.':`An idle agent requests sleep after ${agent.idle_grace_seconds||'a brief'}${agent.idle_grace_seconds?'s':''}; active operations keep it awake.`}</span>}</div>
    <div className="agent-sleep-facts"><div><small>LAST CONTACT</small><strong>{formatTime(agent.last_seen)}</strong></div><div><small>NEXT EXPECTED CHECK-IN</small><strong>{agent.connection_state==='sleeping'?formatTime(agent.expected_checkin):checkin?agent.online===false?'Not scheduled':'After next sleep':'Continuous session'}</strong></div><div><small>{agent.connection_state==='sleeping'?'MARK LOST AFTER':'CURRENT CADENCE'}</small><strong>{agent.connection_state==='sleeping'?formatTime(agent.sleep_lost_after):checkin?`${sleepIntervalLabel(configured)} ±${configuredJitter}%`:'No sleep interval'}</strong></div></div>
    <div className={'agent-sleep-editor '+(!editable?'is-disabled':'')}><div className="agent-sleep-editor-head"><div><h4>Connection policy</h4><p>{agent.connection_state==='sleeping'?'Changes are saved now and sent at the next check-in.':'Changes apply to this agent now and remain saved for later callbacks.'}</p></div></div><div className="agent-sleep-mode" role="group" aria-label="Connection mode"><button type="button" className={!plannedCheckin?'selected':''} disabled={!editable} onClick={()=>setSeconds(0)}>Continuous <small>Keep session open</small></button><button type="button" className={plannedCheckin?'selected':''} disabled={!editable} onClick={()=>setSeconds(configured>0?configured:900)}>Check-in <small>Sleep when idle</small></button></div><div className="agent-sleep-fields"><label><span>Interval <small>seconds between check-ins</small></span><input type="number" inputMode="numeric" min="1" max="86400" disabled={!editable||!plannedCheckin} value={plannedCheckin?seconds:''} onChange={e=>setSeconds(Number(e.target.value))} placeholder="900"/></label><label><span>Jitter <small>percent either side of interval</small></span><div className="agent-sleep-percent"><input type="number" inputMode="numeric" min="0" max="50" disabled={!editable||!plannedCheckin} value={jitter} onChange={e=>setJitter(Number(e.target.value))}/><span>%</span></div></label></div><div className="agent-sleep-actions"><span>{plannedCheckin?`Sleep ${sleepIntervalLabel(seconds)} ±${jitter}% after the idle grace.`:'The agent will maintain a continuous session.'}</span><button disabled={!editable||busy||!dirty||!valid} onClick={save}>{busy?'Applying…':'Apply policy'}</button></div></div>
    {!supported&&<small className="agent-sleep-warning" role="note">This agent build does not support sleep controls. Build a new payload to enable check-in mode.</small>}{supported&&agent.online===false&&agent.connection_state!=='sleeping'&&<small className="agent-sleep-warning" role="note">Policy changes require a check-in. Retained timing and history remain visible above.</small>}{error&&<small className="agent-sleep-warning" role="alert">{error}</small>}{saved&&<small className="agent-sleep-saved" role="status">Policy saved for this agent{agent.connection_state==='sleeping'?' and queued for its next check-in':''}.</small>}
  </section>;
}
function AgentOverviewRoutes({agent,agents,client,openRoutes,onRefresh}:{agent:Agent;agents:Agent[];client:{operator_only:boolean;session_id:string}|null;openRoutes:()=>void;onRefresh:()=>Promise<void>}){
  type SavedRoute={prefix:string;agent_id:string;manual:boolean;disabled:boolean;installed:boolean};
  const [routes,setRoutes]=useState<SavedRoute[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=()=>api<SavedRoute[]>('/client/routes').then(setRoutes).catch(e=>setError(String(e)));
  useEffect(()=>{load()},[agent.id]);
  const act=async(prefix:string,enabled:boolean,create=false)=>{setBusy(true);setError('');try{await api('/client/routes',create?'POST':'PUT',create?{prefix,agent_id:agent.id,manual:false}:{prefix,agent_id:agent.id,enabled});await load();await onRefresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
  const own=routes.filter(route=>route.agent_id===agent.id),canInstall=!!client?.session_id&&!client.operator_only;
  return <div className="agent-overview-routes"><div className="agent-overview-heading"><h3>Client routes through this agent</h3><button onClick={openRoutes}>Open Routes to add a custom CIDR</button></div>
    {agent.advertised_routes?.map(prefix=>{const saved=own.find(route=>route.prefix===prefix),other=routes.find(route=>route.prefix===prefix&&route.agent_id!==agent.id&&!route.disabled),otherAgent=agents.find(item=>item.id===other?.agent_id);return <div className="route-item" key={prefix}><div><strong>{prefix}</strong><small>{other?`Accepted through ${otherAgent?.nickname||otherAgent?.hostname||other.agent_id.slice(0,12)} on this client`:'Advertised by this agent'}</small></div><span className={'badge '+(saved?.installed?'good':'muted')}>{saved?.disabled?'Off':saved?.installed?'Installed':saved?'Pending':other?'Assigned elsewhere':'Available'}</span>{other&&!saved?<button onClick={openRoutes}>Manage</button>:<button disabled={busy||(!saved?.installed&&!canInstall)} onClick={()=>act(prefix,!!saved?.disabled,!saved)}>{!saved?'Accept':saved.disabled?'Enable':'Disable'}</button>}</div>})}
    {own.filter(route=>route.manual&&!agent.advertised_routes?.includes(route.prefix)).map(route=><div className="route-item" key={route.prefix}><div><strong>{route.prefix}</strong><small>Saved custom route</small></div><span className={'badge '+(route.installed?'good':'muted')}>{route.disabled?'Off':route.installed?'Installed':'Pending'}</span><button disabled={busy||route.disabled&&!canInstall} onClick={()=>act(route.prefix,route.disabled)}>{route.disabled?'Enable':'Disable'}</button></div>)}
    {!agent.advertised_routes?.length&&!own.length&&<Empty text="No routes advertised or saved for this agent"/>}
    {!canInstall&&<small>Route changes require a VPN client with a TUN device.</small>}{error&&<p className="control-error" role="alert">{error}</p>}
  </div>
}
type ConsoleFile={name:string;size:number;download:string};
type ConsoleLine={kind:'command'|'output'|'error'|'file';text:string;source?:string;file?:ConsoleFile;requestID?:number};
type ConsoleEntry={id:number;at:string;source:string;kind:'command'|'output'|'error'|'stderr'|'exit'|'file';text:string};
function consoleLineFromEntry(entry:ConsoleEntry):ConsoleLine {return {kind:entry.kind==='command'?'command':entry.kind==='error'?'error':entry.kind==='file'?'file':'output',source:entry.source,file:entry.kind==='file'?parseConsoleFile(entry.text)||undefined:undefined,text:entry.kind==='exit'?`[exit ${entry.text}]\n`:entry.kind==='stderr'?`[stderr] ${entry.text}`:entry.kind==='file'?'':entry.text}}
function parseConsoleFile(data:string):ConsoleFile|null {try{const file=JSON.parse(data) as ConsoleFile;return typeof file.name==='string'&&typeof file.size==='number'&&/^\/api\/transfers\/[a-f0-9]{64}\/download$/.test(file.download)?file:null}catch{return null}}
const agentConsoleLog=new Map<string,ConsoleLine[]>();
const agentConsoleCommands=new Map<string,string[]>();
function ConsoleText({entry}:{entry:ConsoleLine}){
  if(entry.kind==='file')return entry.file?<a href={entry.file.download} download>Download {entry.file.name} ({entry.file.size.toLocaleString()} bytes)</a>:<>Received file link is unavailable.</>;
  if(entry.kind!=='output'||!entry.text.trimStart().startsWith('UNDERTOW  GUI CLIENT / AGENT COMMANDS'))return <>{entry.text}</>;
  return <div className="console-help">{entry.text.split('\n').map((line,index)=>{
    if(line.startsWith('UNDERTOW  '))return <div className="console-help-title" key={index}>{line}</div>;
    if(line.startsWith('──'))return <div className="console-help-rule" key={index}>{line}</div>;
    if(line.startsWith('◆ '))return <div className="console-help-heading" key={index}>{line}</div>;
    const command=/^  (.+?)\s{2,}(.+)$/.exec(line);
    if(command)return <div className="console-help-row" key={index}><span>{command[1]}</span><span>{command[2]}</span></div>;
    return <div className="console-help-note" key={index}>{line||'\u00a0'}</div>;
  })}</div>
}
function AgentCommandConsole({agent,openShell,readOnly=false}:{agent:Agent;openShell:()=>void;readOnly?:boolean}){
  const [lines,setLines]=useState<ConsoleLine[]>(()=>agentConsoleLog.get(agent.id)||[{kind:'output',text:`Attached to ${agent.hostname||agent.id}. Type help for Undertow agent commands.\n`}]);
  const [history,setHistory]=useState<ConsoleEntry[]>([]);
  const [command,setCommand]=useState(''),[pending,setPending]=useState(0),[historyIndex,setHistoryIndex]=useState(-1);
  const outputRef=useRef<HTMLDivElement>(null);
  const activeCommands=useRef(new Map<number,AbortController>());
  const nextRequestID=useRef(0);
  const pendingRef=useRef(0);
  const seenHistory=useRef(new Set<number>()),loadedHistory=useRef(false);
  useEffect(()=>{let mounted=true;const load=()=>api<ConsoleEntry[]>(`/agents/${encodeURIComponent(agent.id)}/console-history`).then(entries=>{if(!mounted)return;setHistory(entries);const fresh=entries.filter(entry=>!seenHistory.current.has(entry.id));entries.forEach(entry=>seenHistory.current.add(entry.id));if(!loadedHistory.current){loadedHistory.current=true;if(pendingRef.current===0)setLines(entries.length?entries.map(consoleLineFromEntry):[{kind:'output',text:`Attached to ${agent.hostname||agent.id}. Type help for Undertow agent commands.\n`}])}else{const moduleLines=fresh.filter(entry=>entry.source==='modules').map(consoleLineFromEntry);if(moduleLines.length)setLines(current=>[...current,...moduleLines].slice(-300))}agentConsoleCommands.set(agent.id,entries.filter(entry=>entry.kind==='command'&&entry.source==='console').map(entry=>entry.text).reverse().slice(0,100))}).catch(()=>{});load();const listener=(event:Event)=>{if((event as CustomEvent<{agentID:string}>).detail?.agentID===agent.id)load()};window.addEventListener('undertow-console-updated',listener);return()=>{mounted=false;window.removeEventListener('undertow-console-updated',listener)}},[agent.id]);
  useEffect(()=>{agentConsoleLog.set(agent.id,lines);outputRef.current?.scrollTo({top:outputRef.current.scrollHeight})},[agent.id,lines]);
  const appendFor=(requestID:number,entry:ConsoleLine)=>setLines(current=>{const lines=[...current];const start=lines.findIndex(item=>item.kind==='command'&&item.requestID===requestID);if(start<0)lines.push(entry);else{const next=lines.findIndex((item,index)=>index>start&&item.kind==='command');lines.splice(next<0?lines.length:next,0,{...entry,requestID})}return lines.slice(-300)});
  const submit=()=>{
    const line=command.trim();if(!line||readOnly)return;
    setCommand('');setHistoryIndex(-1);
    if(line==='clear'||line==='cls'){setLines([]);return}
    const previous=agentConsoleCommands.get(agent.id)||[];
    agentConsoleCommands.set(agent.id,[line,...previous].slice(0,100));
    const requestID=++nextRequestID.current;
    setLines(current=>[...current,{kind:'command' as const,text:line,requestID}].slice(-300));
    pendingRef.current++;setPending(pendingRef.current);
    const controller=new AbortController();activeCommands.current.set(requestID,controller);
    void (async()=>{
    try{
      const response=await fetch(`/api/agents/${encodeURIComponent(agent.id)}/command-stream`,{method:'POST',headers:{'Content-Type':'application/json','X-Undertow-CSRF':csrfToken()},body:JSON.stringify({line}),signal:controller.signal});
      if(!response.ok)throw new Error((await response.text())||response.statusText);
      if(!response.body)throw new Error('Command output stream unavailable');
      const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';
      for(;;){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});let newline;
        while((newline=pending.indexOf('\n'))>=0){const row=pending.slice(0,newline);pending=pending.slice(newline+1);if(!row)continue;const event=JSON.parse(row) as {kind:string;data:string};if(event.kind==='shell')openShell();else if(event.kind==='file')appendFor(requestID,{kind:'file',text:'',file:parseConsoleFile(event.data)||undefined});else appendFor(requestID,{kind:event.kind==='error'?'error':'output',text:event.kind==='exit'?`[exit ${event.data}]\n`:event.kind==='stderr'?`[stderr] ${event.data}`:event.data})}
      }
    }catch(e){appendFor(requestID,{kind:(e as Error).name==='AbortError'?'output':'error',text:(e as Error).name==='AbortError'?'Command stopped.\n':String(e)})}finally{activeCommands.current.delete(requestID);pendingRef.current--;setPending(pendingRef.current);window.dispatchEvent(new CustomEvent('undertow-console-updated',{detail:{agentID:agent.id}}))}
    })();
  };
  return <div className="agent-command-console"><div className="command-console-bar"><SquareTerminal size={15}/><strong>UNDERTOW AGENT CONSOLE</strong><span>{agent.hostname||short(agent.id)}</span></div><div className="console-main"><div className="command-console-output" ref={outputRef} role="log" aria-live="polite">{lines.map((entry,i)=><div key={i} className={'command-entry '+entry.kind}>{entry.source==='modules'&&entry.kind==='command'&&<span className="console-source">MODULES TAB </span>}{entry.kind==='command'&&<span className="prompt-marker">undertow[{agent.hostname||short(agent.id)}]&gt; </span>}<ConsoleText entry={entry}/></div>)}{pending>0&&<div className="command-entry output">{agent.connection_state==='sleeping'?'Waiting for next check-in':'Running'} · {pending} pending command{pending===1?'':'s'}</div>}</div><aside className="console-history"><strong>HISTORY</strong>{history.filter(entry=>entry.kind==='command').slice(-100).reverse().map(entry=><div className="console-history-row" key={entry.id} title={`${entry.at} · ${entry.source}`}><small>{entry.source==='modules'?'MODULE':'CONSOLE'} · {entry.at}</small>{entry.source==='console'?<button disabled={readOnly} onClick={()=>setCommand(entry.text)}>{entry.text}</button>:<span>{entry.text}</span>}</div>)}{!history.some(entry=>entry.kind==='command')&&<p>No commands yet.</p>}</aside></div><div className="command-console-input"><span className="prompt-marker">›</span><input disabled={readOnly} aria-label="Undertow agent command" placeholder="Type an Undertow command, or help" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submit()}else if(e.key==='ArrowUp'){e.preventDefault();const h=agentConsoleCommands.get(agent.id)||[];const next=Math.min(historyIndex+1,h.length-1);if(next>=0){setHistoryIndex(next);setCommand(h[next])}}else if(e.key==='ArrowDown'){e.preventDefault();const h=agentConsoleCommands.get(agent.id)||[];const next=historyIndex-1;setHistoryIndex(next);setCommand(next<0?'':h[next])}}}/><button disabled={readOnly||!command.trim()} onClick={submit}>{pending?'Queue':'Run'}</button>{pending>0&&<button className="command-stop" onClick={()=>activeCommands.current.values().next().value?.abort()}>Stop current</button>}</div></div>
}
function LiveShellPanel({agentID,online}:{agentID:string;online:boolean}){const [requested,setRequested]=useState(false);return <div className="live-shell-panel">{requested?<><div className="live-shell-actions"><span>{online?'Live shell requested':'Waiting for agent check-in'} · {short(agentID)}</span><button onClick={()=>setRequested(false)}>Cancel / close session</button></div><TerminalPanel agentID={agentID} waiting={!online}/></>:<div className="shell-start"><SquareTerminal size={28}/><h3>Live OS shell</h3><p>Starts a separate interactive agent session only when requested. The Undertow agent command console is in the Console tab.</p><button onClick={()=>setRequested(true)}>{online?'Start live shell':'Start at next check-in'}</button></div>}</div>}
function TerminalPanel({agentID,waiting}:{agentID:string;waiting:boolean}){
  const mount=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!mount.current)return;const term=new Terminal({cursorBlink:true,convertEol:true,fontFamily:'Consolas, monospace',fontSize:13,theme:{background:'#0a0d0f',foreground:'#d8ddd9',cursor:'#f2ad42'}});term.open(mount.current);term.writeln(waiting?'Request submitted. Waiting for the next agent check-in…':'Opening requested session…');const scheme=location.protocol==='https:'?'wss':'ws';const socket=new WebSocket(`${scheme}://${location.host}/api/agents/${encodeURIComponent(agentID)}/terminal?csrf=${encodeURIComponent(csrfToken())}`);socket.onmessage=e=>{try{const msg=JSON.parse(e.data);if(msg.type==='ready'){term.clear();return}if(msg.type==='output'||msg.type==='stderr')term.write(msg.data);else if(msg.type==='error')term.writeln(`\r\n${msg.data}`);else if(msg.type==='exit')term.writeln(`\r\nSession ended ${msg.data}`)}catch{}};socket.onclose=()=>term.writeln('\r\nSession disconnected.');const disposable=term.onData(data=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'input',data}))});return()=>{disposable.dispose();socket.close();term.dispose()}},[agentID]);
  return <div className="terminal-shell"><div className="terminal-title"><SquareTerminal size={15}/> Live OS shell <span>{short(agentID)}</span></div><div ref={mount} className="terminal-mount"/></div>
}
function StartJob({agentID,act,busy}:{agentID:string;act:(fn:()=>Promise<unknown>)=>void;busy:boolean}){
  const [program,setProgram]=useState(''),[args,setArgs]=useState<string[]>([]);
  return <section className="job-start"><div><strong>Start background job</strong><span>Runs one program directly on this agent. Arguments are passed exactly as entered; no shell is opened.</span></div><div className="job-start-fields"><label>Program<input aria-label="Job program" value={program} onChange={event=>setProgram(event.target.value)} placeholder="Executable path or name"/></label>{args.map((arg,index)=><label key={index}>Argument {index+1}<span><input aria-label={`Job argument ${index+1}`} value={arg} onChange={event=>setArgs(current=>current.map((value,i)=>i===index?event.target.value:value))}/><button type="button" aria-label={`Remove argument ${index+1}`} onClick={()=>setArgs(current=>current.filter((_,i)=>i!==index))}>×</button></span></label>)}</div><div className="job-start-actions"><button type="button" onClick={()=>setArgs(current=>[...current,''])}>+ Argument</button><button type="button" disabled={busy||!program.trim()} onClick={()=>act(()=>api(`/agents/${encodeURIComponent(agentID)}/jobs`,'POST',{argv:[program.trim(),...args]}))}>Start job</button></div></section>
}
function RelaysView({agents,relays,act,busy,onPayload}:{agents:Agent[];relays:{agent_id:string;bind:string;state?:string}[];act:(fn:()=>Promise<unknown>)=>void;busy:boolean;onPayload:(target:{agentID:string;bind:string})=>void}){
  const [agent,setAgent]=useState(''),[bind,setBind]=useState(''),[mode,setMode]=useState<'tcp'|'smb'>('tcp'),[stop,setStop]=useState<{agent_id:string;bind:string}|null>(null);
  const selected=agents.find(a=>a.id===agent);
  return <div className="panel"><h2>Agent relay listeners</h2><p>A relay carries child agent sessions. Starting a listener does not build or run a child payload.</p>
    <div className="form-line"><select aria-label="Relay parent agent" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Select agent</option>{agents.map(a=><option key={a.id} value={a.id}>{a.nickname||a.hostname||short(a.id)} · {a.id.slice(0,8)}</option>)}</select><select aria-label="Relay carrier" value={mode} onChange={e=>{setMode(e.target.value as 'tcp'|'smb');setBind('')}}><option value="tcp">TCP</option><option value="smb">SMB named pipe</option></select><input aria-label="Relay bind address" placeholder={mode==='smb'?'\\\\.\\pipe\\relay-name':'0.0.0.0:8443 (default)'} value={bind} onChange={e=>setBind(e.target.value)}/><button disabled={busy||!selected||mode==='smb'&&(selected.os?.toLowerCase()!=='windows'||!bind.trim())} onClick={()=>act(()=>api(`/agents/${encodeURIComponent(agent)}/relays`,'POST',{bind:bind.trim()}))}>Start relay</button></div>
    <p className="control-note">{mode==='smb'?<>SMB named pipes require a Windows parent and a child that can access its SMB service. Use <code>\\.\pipe\NAME</code> on the parent and <code>\\PARENT_HOST\pipe\NAME</code> in the child profile. Windows authenticates pipe access; Undertow authenticates the child session.</>:'The default listens on all parent IPv4 interfaces. Use the parent’s reachable IP or hostname, not 0.0.0.0, in the child profile. Choose a specific interface if needed.'}</p>
    {relays.length?relays.map(r=><div className="data-row" key={r.agent_id+r.bind}><Cable size={15}/><strong>{r.bind}</strong><span>{r.state==='pending'?`Pending on ${agents.find(a=>a.id===r.agent_id)?.hostname||short(r.agent_id)} · listener starts at next check-in`:r.bind.startsWith('\\\\.\\pipe\\')?`Pipe open on ${agents.find(a=>a.id===r.agent_id)?.hostname||short(r.agent_id)} · child needs SMB access and Windows authentication`:`TCP bound on ${agents.find(a=>a.id===r.agent_id)?.hostname||short(r.agent_id)} · child needs inbound access under the host firewall policy`}</span><button disabled={busy||r.state==='pending'} onClick={()=>onPayload({agentID:r.agent_id,bind:r.bind})}>Create child payload</button><button className="text-button" disabled={busy} onClick={()=>setStop(r)}>{r.state==='pending'?'Cancel':'Stop'}</button></div>):<Empty text="No relays configured"/>}
    {stop&&<div className="control-confirm" role="alertdialog" aria-label="Confirm relay stop"><div><strong>Stop relay {stop.bind}?</strong><p>Child sessions using this listener will disconnect and may reconnect when the relay returns.</p></div><button disabled={busy} onClick={()=>{act(()=>api(`/agents/${encodeURIComponent(stop.agent_id)}/relays?bind=${encodeURIComponent(stop.bind)}`,'DELETE'));setStop(null)}}>Confirm stop</button><button onClick={()=>setStop(null)}>Cancel</button></div>}
  </div>
}
function StatusView({status,client}:{status:Status|null;client:{session_id:string;transport:string;operator_only:boolean}|null}){return <div className="two-column"><section className="panel"><h2>Local client</h2><Info label="Session ID" value={client?.session_id||'Disconnected'}/><Info label="Carrier" value={client?.transport||'Unknown'}/><Info label="Mode" value={client?.operator_only?'Operator only':'VPN client'}/></section><section className="panel"><h2>Undertow server</h2><Info label="Fingerprint" value={status?.server.fingerprint||'Unknown'}/><Info label="Listeners" value={String(status?.server.listeners?.length||0)}/><Info label="Connected agents" value={String(status?.agents.filter(a=>a.online!==false).length||0)}/></section></div>}
function SettingsView({status,client,operator,revision,onRefresh,showArchived,onArchivedVisibility}:{status:Status|null;client:{session_id:string;transport:string;operator_only:boolean;vpn:boolean;internal:boolean}|null;operator:OperatorAccount|null;revision?:string;onRefresh:()=>Promise<void>;showArchived:boolean;onArchivedVisibility:(show:boolean)=>Promise<void>}){
  const [section,setSection]=useState<'Client'|'Carriers'|'Agents'|'Identity'|'Status'|'Logs'>('Client');
  return <><PageHeader title="Settings" description="Client routing, shared server listeners, operator identity, and diagnostics."/><div className="tabs settings-tabs">{(['Client','Carriers','Agents','Identity','Status','Logs'] as const).map(name=><button key={name} className={section===name?'active':''} onClick={()=>setSection(name)}>{name}</button>)}</div>
    {section==='Client'&&<RoutingModeView client={client} onChange={onRefresh}/>}
    {section==='Carriers'&&<><ServerPublicHost current={status?.server.public_host||''} onSaved={onRefresh}/><TransportsView revision={revision} currentCarrier={client?.session_id?client.transport:undefined}/></>}
    {section==='Agents'&&<section className="panel preferences-panel"><h2>Archived agents</h2><p>Archiving hides a disconnected agent from Agents and Topology. Its retained records remain on the server. If it reconnects, Undertow restores it automatically.</p><label className="archive-visibility"><input type="checkbox" checked={showArchived} onChange={event=>void onArchivedVisibility(event.target.checked)}/><span>Show archived agents in Agents and Topology</span></label><small>{status?.agents.filter(agent=>agent.archived).length||0} archived agent records</small></section>}
    {section==='Identity'&&<OperatorSettings me={operator}/>}
    {section==='Status'&&<StatusView status={status} client={client}/>}
    {section==='Logs'&&<WorkerLogsView/>}
  </>
}
function ServerPublicHost({current,onSaved}:{current:string;onSaved:()=>Promise<void>}){
  const [host,setHost]=useState(current),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>setHost(current),[current]);
  return <section className="panel preferences-panel"><h2>Server public address</h2><p>Set the IP or hostname operators should use for new payload profiles. This is shared server metadata; Undertow does not probe an external IP service.</p><div className="form-line"><input aria-label="Server public IP or hostname" placeholder="Public IP or DNS hostname" value={host} onChange={e=>setHost(e.target.value)} maxLength={253}/><button disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{await api('/server-public-host','PUT',{host:host.trim()});await onSaved();setMessage('Saved on server')}catch(e){setMessage(String(e))}finally{setBusy(false)}}}>Save address</button></div>{message&&<small role="status">{message}</small>}</section>
}

class GUIErrorBoundary extends Component<{children:ReactNode},{error:string}> {
  state={error:''};
  static getDerivedStateFromError(error:unknown){return {error:error instanceof Error?error.message:String(error)}}
  render(){return this.state.error?<main className="gui-crash"><h1>View could not be displayed</h1><p>{this.state.error}</p><button onClick={()=>location.reload()}>Reload GUI</button></main>:this.props.children}
}
createRoot(document.getElementById('root')!).render(<GUIErrorBoundary><App/></GUIErrorBoundary>);
