import {useEffect,useState} from 'react';
import {api} from './api';

export type OperatorAccount={id:string;display_name:string;role:'operator'|'team_leader';disabled:boolean;revoked:boolean};

export function OperatorSettings({me}:{me:OperatorAccount|null}){
  const [accounts,setAccounts]=useState<OperatorAccount[]>([]),[id,setID]=useState(''),[displayName,setDisplayName]=useState(''),[role,setRole]=useState<'operator'|'team_leader'>('operator'),[password,setPassword]=useState(''),[resetID,setResetID]=useState(''),[resetPassword,setResetPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const refresh=()=>api<OperatorAccount[]>('/operators').then(setAccounts).catch(e=>setError(String(e)));
  useEffect(()=>{if(me?.role==='team_leader')void refresh()},[me?.role]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
  if(!me)return <section className="panel preferences-panel"><h2>Operator identity</h2><p>Connect to see your authenticated account.</p></section>;
  return <section className="panel preferences-panel operator-accounts"><h2>Authenticated operator</h2><p><strong>{me.display_name}</strong> · {me.id} · {me.role==='team_leader'?'Team Leader':'Operator'}</p>
    {me.role==='team_leader'&&<><h3>Accounts</h3><p>Changes to a connected account close its sessions. The account can reconnect with its current credentials when enabled.</p><button type="button" disabled={busy} onClick={()=>void refresh()}>Refresh accounts</button>
      {accounts.map(a=><div key={a.id}><div className="data-row"><strong>{a.display_name}</strong><span>{a.id} · {a.role==='team_leader'?'Team Leader':'Operator'} · {a.revoked?'Revoked':a.disabled?'Disabled':'Active'}</span><button disabled={busy||a.revoked} onClick={()=>void act(()=>api(`/operators/${encodeURIComponent(a.id)}`,'PUT',{role:a.role==='team_leader'?'operator':'team_leader'}))}>{a.role==='team_leader'?'Demote':'Promote'}</button><button disabled={busy||a.revoked} onClick={()=>void act(()=>api(`/operators/${encodeURIComponent(a.id)}`,'PUT',{disabled:!a.disabled}))}>{a.disabled?'Enable':'Disable'}</button><button disabled={busy||a.revoked} onClick={()=>{setResetID(a.id);setResetPassword('')}}>Reset password</button><button disabled={busy||a.revoked} onClick={()=>{if(window.confirm(`Permanently revoke ${a.id}? This account ID cannot be reused.`))void act(()=>api(`/operators/${encodeURIComponent(a.id)}`,'DELETE'))}}>Revoke</button></div>{resetID===a.id&&<div className="form-line"><input aria-label={`New password for ${a.id}`} type="password" autoComplete="new-password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder="New password (12-72 bytes)"/><button disabled={busy||!resetPassword} onClick={()=>void act(async()=>{await api(`/operators/${encodeURIComponent(a.id)}`,'PUT',{password:resetPassword});setResetID('');setResetPassword('')})}>Save new password</button><button onClick={()=>{setResetID('');setResetPassword('')}}>Cancel</button></div>}</div>)}
      <h3>Create account</h3><div className="form-line"><input aria-label="New operator ID" placeholder="Account ID" value={id} onChange={e=>setID(e.target.value)}/><input aria-label="New operator display name" placeholder="Display name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/><select aria-label="New operator role" value={role} onChange={e=>setRole(e.target.value as 'operator'|'team_leader')}><option value="operator">Operator</option><option value="team_leader">Team Leader</option></select><input aria-label="New operator password" type="password" autoComplete="new-password" placeholder="Password (12-72 bytes)" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>void act(async()=>{await api('/operators','POST',{id,display_name:displayName,role,password});setID('');setDisplayName('');setPassword('')})}>Create</button></div>
    </>}{error&&<p className="control-error" role="alert">{error}</p>}
  </section>
}
