import {useEffect, useState} from 'react';
import {Boxes, Download, FileCode2, PackagePlus, Plus, RefreshCw} from 'lucide-react';
import {api} from './api';
import {PayloadRetrieval} from './PayloadRetrieval';

type Profile = {id:string;name:string;created:string;server:string;transport:string;domain?:string;fingerprint:string;auth_mode:string;payload_profile?:string;websocket_path?:string;tls_server_name?:string;tls_insecure_skip_verify?:boolean;advertised_routes?:string[];denied_capabilities?:string};
type Artifact = {id:string;profile:string;platform:string;architecture:string;filename:string;size:number;sha256:string;server_path:string;hosted:boolean;revoked?:boolean;created:string};
type Hosted = Artifact & {retrieval:string;retrieval_path:string;tls_self_signed?:boolean};
type ProfileDraft = {name:string;server:string;transport:string;domain:string;payload_profile:string;websocket_path:string;tls_server_name:string;tls_insecure_skip_verify:boolean;advertised_routes:string;denied_capabilities:string};
const blankProfile:ProfileDraft={name:'',server:'',transport:'quic',domain:'',payload_profile:'auto',websocket_path:'',tls_server_name:'',tls_insecure_skip_verify:false,advertised_routes:'',denied_capabilities:''};
const targets=[{value:'windows/amd64',label:'Windows · x64'},{value:'linux/amd64',label:'Linux · x64'},{value:'linux/arm64',label:'Linux · ARM64'}];

function profileDraft(p:Profile):ProfileDraft {
  return {name:p.name,server:p.server,transport:p.transport,domain:p.domain||'',payload_profile:p.payload_profile||'auto',websocket_path:p.websocket_path||'',tls_server_name:p.tls_server_name||'',tls_insecure_skip_verify:!!p.tls_insecure_skip_verify,advertised_routes:(p.advertised_routes||[]).join(', '),denied_capabilities:p.denied_capabilities||''};
}
function profileRequest(p:ProfileDraft,create:boolean) {
  return {name:create?p.name.trim():undefined,server:p.server.trim(),transport:p.transport,domain:p.transport==='dns'?p.domain.trim():'',payload_profile:p.transport==='dns'?p.payload_profile:'auto',websocket_path:p.transport==='websocket'?p.websocket_path.trim():'',tls_server_name:p.transport==='relay'?'':p.tls_server_name.trim(),tls_insecure_skip_verify:p.transport==='relay'?false:p.tls_insecure_skip_verify,advertised_routes:p.advertised_routes.split(',').map(value=>value.trim()).filter(Boolean),denied_capabilities:p.denied_capabilities.trim()};
}
function downloadText(text:string,filename:string) {
  const href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));
  const anchor=document.createElement('a');anchor.href=href;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(href),2000);
}

function reachableAddress(publicHost?:string,connectedAddress?:string){
  if(!publicHost)return connectedAddress||'';
  try{const port=new URL(`tcp://${connectedAddress}`).port;return `${publicHost.includes(':')?`[${publicHost}]`:publicHost}${port?`:${port}`:''}`}catch{return publicHost}
}
export function PayloadView({revision,serverAddress,publicHost,clientTransport,relayTarget}:{revision?:string;serverAddress?:string;publicHost?:string;clientTransport?:string;relayTarget?:{agentID:string;bind:string}|null}) {
  const [tab,setTab]=useState<'profiles'|'build'|'artifacts'|'retrieval'>('profiles');
  const [profiles,setProfiles]=useState<Profile[]>([]);
  const [artifacts,setArtifacts]=useState<Artifact[]>([]);
  const [selectedProfile,setSelectedProfile]=useState('');
  const [draft,setDraft]=useState<ProfileDraft>(blankProfile);
  const [profileMode,setProfileMode]=useState<'create'|'edit'>('create');
  const [buildProfile,setBuildProfile]=useState('');
  const [target,setTarget]=useState('windows/amd64');
  const [filename,setFilename]=useState('');
  const [selectedArtifact,setSelectedArtifact]=useState('');
  const [hosted,setHosted]=useState<Hosted|null>(null);
  const [script,setScript]=useState<{text:string;filename:string}|null>(null);
  const [scriptFormat,setScriptFormat]=useState<'powershell'|'shell'>('powershell');
  const [confirm,setConfirm]=useState<'delete-profile'|'delete-artifact'|'revoke'|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const load=async()=>{const [p,a]=await Promise.all([api<Profile[]|null>('/profiles'),api<Artifact[]|null>('/artifacts')]);setProfiles(p||[]);setArtifacts(a||[])};
  useEffect(()=>{load().catch(e=>setError(String(e)))},[revision]);
  const suggestedAddress=reachableAddress(publicHost,serverAddress);
  useEffect(()=>{if(suggestedAddress)setDraft(current=>current.name||current.server?current:{...current,server:suggestedAddress,transport:clientTransport||current.transport})},[suggestedAddress,clientTransport]);
  useEffect(()=>{if(!relayTarget)return;setTab('profiles');setProfileMode('create');setSelectedProfile('');setDraft({...blankProfile,transport:'relay',server:relayTarget.bind})},[relayTarget]);
  const artifact=artifacts.find(item=>item.id===selectedArtifact);
  const chosenProfile=profiles.find(item=>item.name===buildProfile);
  useEffect(()=>{setHosted(null);setScript(null);setConfirm(null);if(!artifact?.hosted)return;api<Hosted>(`/artifacts/${encodeURIComponent(artifact.id)}/host`).then(setHosted).catch(e=>setError(String(e)))},[artifact?.id,artifact?.hosted]);
  const run=async(operation:()=>Promise<unknown>,message:string,onSuccess?:()=>void)=>{setBusy(true);setError('');setNotice('');try{await operation();await load();setNotice(message);onSuccess?.()}catch(e){setError(String(e))}finally{setBusy(false)}};
  const chooseProfile=(name:string)=>{setSelectedProfile(name);setConfirm(null);const profile=profiles.find(item=>item.name===name);if(profile){setDraft(profileDraft(profile));setProfileMode('edit')}else{setDraft({...blankProfile,server:suggestedAddress,transport:clientTransport||'quic'});setProfileMode('create')}};
  const chooseArtifact=(id:string)=>{setSelectedArtifact(id);setScript(null);setConfirm(null)};
  const selectedProfileData=profiles.find(item=>item.name===selectedProfile);
  return <div className="payload-workspace">
    <div className="payload-tabs"><button className={tab==='profiles'?'active':''} onClick={()=>setTab('profiles')}>Profiles <span>{profiles.length}</span></button><button className={tab==='build'?'active':''} onClick={()=>setTab('build')}>Build payload</button><button className={tab==='artifacts'?'active':''} onClick={()=>setTab('artifacts')}>Artifacts <span>{artifacts.length}</span></button><button className={tab==='retrieval'?'active':''} onClick={()=>setTab('retrieval')}>Retrieval settings</button><button className="payload-refresh" title="Refresh payload records" onClick={()=>load().catch(e=>setError(String(e)))}><RefreshCw size={14}/></button></div>
    {error&&<div className="payload-alert error" role="alert">{error}</div>}{notice&&<div className="payload-alert">{notice}</div>}
    {tab==='retrieval'&&<PayloadRetrieval/>}
    {tab==='profiles'&&<div className="payload-columns"><div className="panel payload-list"><div className="payload-section-title"><h2>Connection profiles</h2><button onClick={()=>chooseProfile('')}><Plus size={13}/> New</button></div>{profiles.length?profiles.map(profile=><button className={'payload-list-item '+(selectedProfile===profile.name?'active':'')} key={profile.id} onClick={()=>chooseProfile(profile.name)}><strong>{profile.name}</strong><span>{profile.transport.toUpperCase()} · {profile.server}</span></button>):<div className="payload-empty">No profiles. Create one to define a payload’s connection settings.</div>}</div>
      <section className="panel payload-form"><span className="eyebrow">{profileMode==='create'?'NEW PROFILE':'PROFILE SETTINGS'}</span><h2>{profileMode==='create'?'Create a profile':selectedProfile}</h2><p>These settings are embedded in future builds. Existing artifacts keep their original profile snapshot.</p>
        {draft.transport==='relay'&&<p className="payload-relay-note">The address below is embedded as the child agent’s relay destination. The payload remains on the Undertow server for download and HTTPS hosting; the relay listener does not serve files. A loopback bind is reachable only from the parent host.</p>}
        <div className="payload-fields"><label>Profile name<input value={draft.name} disabled={profileMode==='edit'} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="e.g. branch-relay"/></label><label>Carrier<select value={draft.transport} onChange={event=>setDraft({...draft,transport:event.target.value})}><option value="quic">QUIC</option><option value="websocket">WebSocket</option><option value="dns">DNS</option><option value="relay">Agent relay</option></select></label><label className="wide">{draft.transport==='relay'?'Child reachable relay address':'Agent reachable server address'}<input value={draft.server} onChange={event=>setDraft({...draft,server:event.target.value})} placeholder="host.example:443"/><small>Use the address the endpoint can reach, including the listener port.</small></label>{draft.transport==='dns'&&<><label>DNS domain<input value={draft.domain} onChange={event=>setDraft({...draft,domain:event.target.value})} placeholder="Delegated domain"/></label><label>DNS payload profile<select value={draft.payload_profile} onChange={event=>setDraft({...draft,payload_profile:event.target.value})}><option value="auto">Auto</option><option value="large">Large</option><option value="small">Small</option></select></label></>}{draft.transport==='websocket'&&<label>WebSocket path<input value={draft.websocket_path} onChange={event=>setDraft({...draft,websocket_path:event.target.value})} placeholder="/undertow"/></label>}{draft.transport!=='relay'&&<><label>TLS server name<input value={draft.tls_server_name} onChange={event=>setDraft({...draft,tls_server_name:event.target.value})} placeholder="Optional"/></label><label className="payload-check"><input type="checkbox" checked={draft.tls_insecure_skip_verify} onChange={event=>setDraft({...draft,tls_insecure_skip_verify:event.target.checked})}/>Allow a self-signed carrier certificate; Undertow still pins the server fingerprint</label></>}<label className="wide">Advertised routes<input value={draft.advertised_routes} onChange={event=>setDraft({...draft,advertised_routes:event.target.value})} placeholder="10.20.0.0/16, 10.30.0.0/24"/><small>Comma separated IPv4 CIDRs. Optional.</small></label><label className="wide">Denied agent capabilities<input value={draft.denied_capabilities} onChange={event=>setDraft({...draft,denied_capabilities:event.target.value})} placeholder="Optional capability list"/></label></div>
        {selectedProfileData&&<div className="payload-profile-facts"><span>Server fingerprint <code>{selectedProfileData.fingerprint}</code></span><span>Created {new Date(selectedProfileData.created).toLocaleString()}</span></div>}
        <div className="payload-actions"><button className="primary" disabled={busy||!draft.server.trim()||(profileMode==='create'&&!draft.name.trim())} onClick={()=>run(()=>api(profileMode==='create'?'/profiles':`/profiles/${encodeURIComponent(selectedProfile)}`,profileMode==='create'?'POST':'PUT',profileRequest(draft,profileMode==='create')),profileMode==='create'?'Profile created':'Profile updated',()=>{if(profileMode==='create'){setBuildProfile(draft.name.trim());setDraft(blankProfile)}})}>{profileMode==='create'?'Create profile':'Save changes'}</button>{profileMode==='edit'&&<><button onClick={()=>{setBuildProfile(selectedProfile);setTab('build')}}>Build from profile</button><button className="danger" onClick={()=>setConfirm('delete-profile')}>Delete profile</button></>}</div>
        {confirm==='delete-profile'&&<div className="payload-confirm">Delete profile {selectedProfile}? Existing artifacts remain. <button disabled={busy} onClick={()=>run(()=>api(`/profiles/${encodeURIComponent(selectedProfile)}`,'DELETE'),`Deleted profile ${selectedProfile}`,()=>chooseProfile(''))}>Confirm delete</button><button onClick={()=>setConfirm(null)}>Cancel</button></div>}
      </section></div>}
    {tab==='build'&&<div className="payload-build panel"><div className="payload-build-heading"><PackagePlus size={28}/><div><span className="eyebrow">EXPLICIT BUILD</span><h2>Build an agent payload</h2><p>Creates a new artifact from a saved profile. No agent is started by building it.</p></div></div>
      <div className="payload-fields"><label className="wide">Profile<select value={buildProfile} onChange={event=>setBuildProfile(event.target.value)}><option value="">Select profile</option>{profiles.map(profile=><option value={profile.name} key={profile.id}>{profile.name}</option>)}</select></label><label>Target platform<select value={target} onChange={event=>setTarget(event.target.value)}>{targets.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Output filename (optional)<input value={filename} onChange={event=>setFilename(event.target.value)} placeholder={target.startsWith('windows')?'e.g. worker.exe':'e.g. worker'}/></label></div>
      {chosenProfile&&<div className="payload-build-summary"><strong>Build settings</strong><span>{chosenProfile.transport.toUpperCase()} → {chosenProfile.server}</span><span>Server pin {chosenProfile.fingerprint}</span><span>Denied capabilities: {chosenProfile.denied_capabilities||'None'}</span>{/^(127\.|localhost|\[::1\])/.test(chosenProfile.server)&&<em>The profile uses a loopback server address. A remote endpoint would reach its own loopback interface.</em>}</div>}
      <button className="primary" disabled={busy||!buildProfile} onClick={()=>{const [platform,architecture]=target.split('/');run(()=>api<Artifact>('/artifacts','POST',{profile:buildProfile,platform,architecture,...(filename.trim()?{filename:filename.trim()}:{})}),`Built a new ${target} artifact`,()=>{setTab('artifacts');setFilename('')})}}>{busy?'Building…':'Build payload'}</button>
    </div>}
    {tab==='artifacts'&&<div className="payload-columns"><div className="panel payload-list"><h2>Built artifacts</h2>{artifacts.length?artifacts.map(item=><button key={item.id} className={'payload-list-item '+(selectedArtifact===item.id?'active':'')} onClick={()=>chooseArtifact(item.id)}><strong>{item.filename}</strong><span>{item.platform}/{item.architecture} · {item.id.slice(0,12)}</span><span className={'payload-state '+(item.revoked?'revoked':item.hosted?'hosted':'')}>{item.revoked?'Enrollment revoked':item.hosted?'Hosted':'Not hosted'}</span></button>):<div className="payload-empty">No artifacts built. Select Build payload to create one from a profile.</div>}</div>
      {artifact?<section className="panel payload-artifact"><span className="eyebrow">SERVER ARTIFACT</span><h2>{artifact.filename}</h2><div className="payload-artifact-facts"><div><span>Payload ID</span><code>{artifact.id}</code></div><div><span>Profile snapshot</span><strong>{artifact.profile}</strong></div><div><span>Target</span><strong>{artifact.platform}/{artifact.architecture}</strong></div><div><span>Created</span><strong>{new Date(artifact.created).toLocaleString()}</strong></div><div><span>Size</span><strong>{(artifact.size/1048576).toFixed(2)} MiB</strong></div><div><span>SHA-256</span><code>{artifact.sha256}</code></div><div><span>Server file</span><code>{artifact.server_path}</code></div></div>
        <div className="payload-actions"><a className="payload-button primary" href={`/api/artifacts/${encodeURIComponent(artifact.id)}/download`} download={artifact.filename}><Download size={13}/>Download verified binary</a>{artifact.hosted?<button disabled={busy} onClick={()=>run(()=>api(`/artifacts/${encodeURIComponent(artifact.id)}/host`,'DELETE',undefined),`Stopped hosting ${artifact.id}`,()=>setHosted(null))}>Unhost</button>:<button disabled={busy} onClick={()=>run(()=>api(`/artifacts/${encodeURIComponent(artifact.id)}/host`,'POST',{}),`Hosted ${artifact.id}`)}>Host on HTTPS listener</button>}</div>
        {artifact.hosted&&<div className="payload-hosted"><strong>Hosted retrieval</strong>{hosted?<><label>Download URL<input readOnly value={hosted.retrieval}/></label><span>Opaque path {hosted.retrieval_path}</span></>:<span>Loading current URL…</span>}</div>}
        <div className="payload-script"><div><FileCode2 size={17}/><strong>Deploy helper</strong><span>Generation only; nothing runs on the endpoint.</span></div><div className="payload-actions"><select value={scriptFormat} onChange={event=>{setScriptFormat(event.target.value as 'powershell'|'shell');setScript(null)}}><option value="powershell">PowerShell</option><option value="shell">POSIX shell</option></select><button disabled={!artifact.hosted||busy} onClick={async()=>{setError('');try{const result=await api<{script:string;filename:string}>(`/artifacts/${encodeURIComponent(artifact.id)}/deploy-script?format=${scriptFormat}`);setScript({text:result.script,filename:result.filename})}catch(e){setError(String(e))}}}>Generate preview</button>{script&&<button onClick={()=>downloadText(script.text,script.filename)}>Download script</button>}</div>{script&&<pre>{script.text}</pre>}</div>
        <div className="payload-danger"><strong>Lifecycle controls</strong><p>Revocation blocks future enrollment with this build; existing agent sessions continue. Deleting removes the server record and hosted file.</p><div className="payload-actions"><button disabled={busy||artifact.revoked} onClick={()=>setConfirm('revoke')}>Revoke enrollment</button><button disabled={busy} onClick={()=>setConfirm('delete-artifact')}>Delete artifact</button></div>{confirm&&confirm!=='delete-profile'&&<div className="payload-confirm">{confirm==='revoke'?'Revoke future enrollment for this artifact?':'Delete this artifact and its server file?'} <button disabled={busy} onClick={()=>run(()=>api(`/artifacts/${encodeURIComponent(artifact.id)}${confirm==='revoke'?'/revoke':''}`,confirm==='revoke'?'POST':'DELETE',confirm==='revoke'?{}:undefined),confirm==='revoke'?'Enrollment revoked':'Artifact deleted',()=>{setConfirm(null);if(confirm==='delete-artifact')setSelectedArtifact('')})}>Confirm</button><button onClick={()=>setConfirm(null)}>Cancel</button></div>}</div>
      </section>:<section className="panel payload-selection"><Boxes size={32}/><h2>Select an artifact</h2><p>Build details, downloads, hosting, and deploy helpers appear here.</p></section>}</div>}
  </div>;
}
